server: # 服务器配置
  port: 8086  # 端口
  servlet: # 新增 servlet 节点
    context-path: / # 应用上下文路径
spring: # Spring配置
  application: # 应用配置
    name: service-code-sandbox # 应用名称
  profiles: # 环境配置
    active: local # 激活的环境
  mail: # 邮件配置
    host: smtp.qq.com        # SMTP主机地址
    username: xxxx@qq.com     # 用户名
    password: xxxx     # 生成的密码（不是用户密码）
    properties: # JavaMail属性
      mail.smtp.auth: true      # 取用认证
      mail.smtp.starttls.enabled: true   # 启用加密连接
      mail.smtp.starttls.required: true   # 启用加密连接
    default-encoding: UTF-8 # 默认编码
  datasource: # 数据源配置
    type: com.alibaba.druid.pool.xa.DruidXADataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver  # 配置MySQL的驱动程序类
    url: jdbc:mysql://127.0.0.1:3306/information_wuledi?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true # 数据库地址
    username: root         # 数据库用户名
    password: xxxx        # 数据库连接密码
    druid: # druid相关配置
      initial-size: 5         # 初始化连接池大小
      min-idle: 10          # 最小维持的连接池大小
      max-active: 50         # 最大支持的连接池大小
      max-wait: 60000          # 最大等待时间（单位：ms）
      time-between-eviction-runs-millis: 60000  # 关闭空闲连接间隔（单位：ms）
      min-evictable-idle-time-millis: 30000   # 连接最小生存时间（单位：ms）
      validation-query: SELECT 1 FROM dual   # 数据库状态检测
      test-while-idle: true        # 申请连接时检测连接是否有效
      test-on-borrow: false        # 申请连接时检测连接是否有效
      test-on-return: false        # 归还连接时检测连接是否有效
      pool-prepared-statements: false     # PSCache缓存
      max-pool-prepared-statement-per-connection-size: 20  # 配置PS缓存
      filters: stat, wall, slf4j       # 开启过滤
      stat-view-servlet: # 监控界面配置
        enabled: true          # 启用Druid监控界面
        allow: 127.0.0.1             # 设置访问白名单
        login-username: wuledi        # 用户名
        login-password: xxxx        # 密码
        reset-enable: true        # 允许重置
        url-pattern: /druid/*        # 访问路径
      web-stat-filter: # Web监控
        enabled: true          # 启动URI监控
        url-pattern: /*         # 跟踪根路径下的全部服务
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*" # 跟踪排除
      filter: # Druid过滤器
        slf4j: # 日志
          enabled: true         # 启用SLF4j监控
          data-source-log-enabled: true     # 启用数据库日志
          statement-executable-sql-log-enable: true # 执行日志
          result-set-log-enabled: true     # ResultSet日志启用
        stat: # SQL监控
          merge-sql: true         # 统计时合并相同的SQL命令
          log-slow-sql: true        # 当SQL执行缓慢时是否要进行记录
          slow-sql-millis: 1        # 设置慢SQL的执行时间标准，单位：ms
        wall: # SQL防火墙
          enabled: true           # 启用SQL防火墙
          config: # 配置防火墙规则
            multi-statement-allow: true     # 允许执行批量SQL
            delete-allow: false       # 禁止执行删除语句
      aop-patterns: "com.wuledi.*.controller.*,com.wuledi.*.service.*,com.wuledi.*.dao.*" # Spring监控
  data: # 数据配置
    redis: # redis配置
      host: 127.0.0.1 # 主机
      port: 6379 # 端口
      password: xxxx # 密码
      database: 0 # 数据库
      lettuce: # lettuce配置
        pool: # 连接池配置
          max-active: 10 # 最大连接数
          max-idle: 10 # 最大空闲连接数
          min-idle: 0 # 最小空闲连接数
          max-wait: 1s # 最大等待时间
          time-between-eviction-runs: 2000    # 每2s回收一次空闲连接

mybatis-plus: # mybatis-plus配置
  mapper-locations: classpath:/mapper/**.xml # mapper.xml路径
  configuration: # 全局配置
    map-underscore-to-camel-case: true # 驼峰命名 https://baomidou.com/reference/#mapunderscoretocamelcase
  global-config: # 通用配置
    db-config: # 数据库配置
      logic-delete-field: isDeleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
# springdoc-openapi项目配置
springdoc:
  swagger-ui: # swagger-ui配置 swagger-ui/index.html
    path: /swagger-ui.html # swagger-ui路径
    tags-sorter: alpha # 标签排序,alpha按字母排序
    operations-sorter: alpha # 操作排序
    enabled: true # 是否启用swagger-ui
  api-docs: # api-docs配置
    path: /v3/api-docs # api-docs路径
    enabled: true # 是否启用api-docs
  group-configs: # 分组配置
    - group: 'default' # 分组名称
      paths-to-match: '/**' # 匹配路径, 表示所有路径都匹配
      packages-to-scan: com.wuledi # 扫描包路径

wuledi:
  codesandbox:
    docker:
      host: tcp://172.27.251.187:2375 # 本地docker主机地址, 用于测试 #  ip addr show 查看ip
      # host: tcp://localhost:2375 # 线上需要修改你的docker主机地址并启用了远程控制
  author: wuledi # 作者
  captcha:
    expiry-seconds: 300 # 验证码过期时间
  config: # 自定义配置项
    jwt: # JWT相关配置
      issuer: wuledi     # 证书签发人
      secret: wuledi.xxxx      # 加密密钥（公共密钥）
      expiry: 720       # 有效时长(小时)
  listener:
    register:
      mail: mail@wuledi.com
  storage: # 存储配置
    qiniu: # 七牛云存储配置
      enabled: true
      access-key: xxxx # 密钥ID
      secret-key: xxxx # 密钥KEY
      domain: xxxx # 域名
      bucket: wuledi # 存储桶