server: # 服务器配置
  port: 18083  # 端口
  servlet: # 新增 servlet 节点
    context-path: / # 应用上下文路径
spring: # Spring配置
  application: # 应用配置
    name: common-security # 应用名称
  profiles: # 环境配置
    active: local # 激活的环境
  data: # 数据配置
    redis: # redis配置
      host: 127.0.0.1 # 主机
      port: 6379 # 端口
      password: xxxx # 密码
      database: 0 # 数据库
      lettuce: # lettuce配置
        pool: # 连接池配置
          max-active: 10 # 最大连接数
          max-idle: 5 # 最大空闲连接数
          min-idle: 0 # 最小空闲连接数
          max-wait: 1s # 最大等待时间
          time-between-eviction-runs: 2000    # 每2s回收一次空闲连接
wuledi:
  author: wuledi # 作者
  config: # 自定义配置项
    jwt: # JWT相关配置
      issuer: wuledi     # 证书签发人
      secret: wuledi-xxx      # 加密密钥（公共密钥）
      expiry: 720       # 有效时长(小时)