server: # 服务器配置
  port: 28086  # 端口
  servlet: # 新增 servlet 节点
    context-path: / # 应用上下文路径
spring: # Spring配置
  application: # 应用配置
    name: ai-memory # 应用名称
  profiles: # 环境配置
    active: local # 激活的环境
  ai:
    memory:
      redis:
        host: 127.0.0.1
        port: 6379
        password: xxxx
        timeout:  5000
    chat:
      memory:
        repository:
          jdbc:
            mysql:
              jdbc-url: jdbc:mysql://127.0.0.1:3306/information_wuledi?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrl
              username: root
              password: xxxx
              driver-class-name: com.mysql.cj.jdbc.Driver  # 配置MySQL的驱动程序类
              enabled: true
  datasource: # 数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver  # 配置MySQL的驱动程序类
    url: jdbc:mysql://127.0.0.1:3306/information_wuledi?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true # 数据库地址
    username: root         # 数据库用户名
    password: xxxx        # 数据库连接密码
  data: # 数据配置
    redis: # redis配置
      host: 127.0.0.1 # 主机
      port: 6379 # 端口
      password: xxxx # 密码
      database: 0 # 数据库
      lettuce: # lettuce配置
        pool: # 连接池配置
          max-active: 10 # 最大连接数
          max-idle: 5 # 最大空闲连接数
          min-idle: 0 # 最小空闲连接数
          max-wait: 1s # 最大等待时间
          time-between-eviction-runs: 2000    # 每2s回收一次空闲连接
wuledi:
  ai:
    memory: # 聊天记录缓存配置
      type: memory # 缓存类型，支持：内存(memory)、mysql(mysql)、redis(redis)