server: # 服务器配置
  port: 28084  # 端口
  servlet: # 新增 servlet 节点
    context-path: / # 应用上下文路径

spring: # Spring配置
  application: # 应用配置
    name: ai-mcp # 应用名称
  ai:
    mcp:
      server:
        name: mcp
        version: 0.0.1
        type: SYNC
        # sse
        stdio: false

wuledi:
  ai:
    mcp:
      pexels:
        api-key: xxxx
